### ISSUE TITLE
Поправить экран просмотра комментария

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/golos-android#118]
1. Пользователь тапает ответить на комментарий.
2. Его редиректит на страницу просмотра комментария.
3. Пользовтаель тапает:
- иконку коменатрия в футоре поста
- тапает по полю ввода поста

![image](https://user-images.githubusercontent.com/30616421/46727354-ac190080-cc80-11e8-974a-75b4e72b6a48.png)
- [ ] Поднять панель ввода комментариев. 
- [ ] Убрать текстовую подсказку о наличии ответов к комментарию.
- [ ] Дать возможность перейти на экран комментирования через иконку комментария в футоре поста

**Comment by yurivlad** [comment]
@jevgenika  Хотел бы уточнить актуальность этого ишью в разрезе https://github.com/GolosChain/golos-android/issues/115
