### ISSUE TITLE
настроить компактную ленту и ночной режим

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/golos-android#16]
- [ ] настроить отображение компактной ленты
- [ ] настроить отображение ночного режима
- [ ] вынести эти функции в настройки, чтобы пользователь мог выбрать альтернативную ленту и цвет

**Comment by BaroH4er** [comment]
Тестирование завершено. [Отчет + чек-лист](https://docs.google.com/spreadsheets/d/18_3uo_bcHP3sJ5oZWbHGWFkAHtWn0LhhLoDdgKQXRt8/edit?usp=sharing).
