### ISSUE TITLE
загрузка и сжатие картинок

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/golos-android#17]
- [ ] обсудить с @b1acksun загрузку и сжатие картинок
- [ ] реализовать загрузку и сжатие картинок

**Comment by BaroH4er** [comment]
Тестирование завершено. Ошибок нет.

- [x] реализовать загрузку и сжатие картинок

**_Заметка_**
_Публикация поста не удалась - 1/10, тригер не обнаружен, воспроизвести не удалось._
