### ISSUE TITLE
добавить стандартное изображение для постов с тегом NSFW

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/golos-android#19]
- [x] В лентах постам с тегом NSFW выставлять картинку по умолчанию, скрывать отображение картинок в ленте тегом NSFW. На странице поста и раскрытом посте отображаем картинку пользователя.

- [x] Отключить ограничения nsfw (Всегда скрывать, Всегда предупреждать) для собственных постов залогиненного пользователя, так как не имеет смысла ограничивать пользователя от его собственного контента. То есть, авторизованный пользователь все свои посты в любых категориях видит в режиме nsfw "Отображать всегда".

- [x] Добавить в настройках отключение скрытия постов слайдером.

- [x] Заменять дефолтную картинку в зависимость от режима: обычный и ночной режимы
![zaglushka_1 2](https://user-images.githubusercontent.com/33282977/34339413-734d3cf4-e97c-11e7-969f-0ccee731b24b.png)
![zaglushka_2](https://user-images.githubusercontent.com/33282977/34339414-7370a932-e97c-11e7-9bb6-5aad61e19d12.png)

смотреть выполненный таск https://github.com/GolosChain/tolstoy/issues/444

**Comment by BaroH4er** [comment]
- [ ] скрывать отображение картинок в ленте тегом NSFW/выставлять картинку по умолчанию
- [ ]  отключить ограничения nsfw для собственных постов 
- [ ]  добавить в настройках отключение скрытия постов слайдером.
- [ ] заменять дефолтную картинку в зависимость от режима: обычный и ночной режимы

Тестирование завершено. Ошибок нет.

**Comment by BaroH4er** [comment]
- [x] скрывать отображение картинок в ленте тегом NSFW/выставлять картинку по умолчанию
- [x]  отключить ограничения nsfw для собственных постов 
- [x]  добавить в настройках отключение скрытия постов слайдером.
- [x] заменять дефолтную картинку в зависимость от режима: обычный и ночной режимы

Тестирование завершено. Ошибок нет.
