### ISSUE TITLE
 сохранять посты в ленте

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/golos-android#25]
- [x]  сохранять посты в ленте - сохранять ленту. Когда пользоватаель стартует приложение снова, оно сразу показывает ленту, и надпись сверху - "обновить".
- [x] добавить кнопку "обновить" ленту
Пользователь тянет ленту вверху, обновление идет по стандартному сценарию.

**Comment by BaroH4er** [comment]
Тест завершён. Ошибок нет. [Отчет + чек-лист](https://docs.google.com/spreadsheets/d/12KnSQ7ylGLNBk8Pqwkmav4lVdqRwTWtYe2AJznk_Mxk/edit?usp=sharing).
