### ISSUE TITLE
В профиля пользователя добавить отображение мощности голоса

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/golos-android#29]
- [x] в профиля пользователя добавить отображение “Батарейки”
По тапу на юзерпик пользователя отображается Мощность его Голоса  “Батарейки” в процентах - количество апвоутов (лайков), которые остались для реализации пользователем в течении суток.
Юзерпик высветляется, на его месте видим количество процентов.
Обводка уменьшается по кругу от синего к красному.
![image](https://user-images.githubusercontent.com/30616421/35630539-5b5ff096-06aa-11e8-815e-74d43191ed8b.png)

**Comment by BaroH4er** [comment]
Тестирование завершено. Ошибок нет. Отображается и функционирует. 

- [x]  “Батарейка” силы голоса в профиле.
