### ISSUE TITLE
[Bug report 15.02.2018 - golos-android] v.0.51 

### ISSUE THREAD

**Issue by BaroH4er** [GolosChain/golos-android#32]
## Счетчик постов 

**Проблема**: Счетчик постов суммирует публикации и комментарии.

**Воспроизведение**:
1. Открыть приложение.
2. Открыть кабинет пользователя.
3. Запомнить число указанное на счетчике постов.
4. Создать пост.
5. Добавить комментарий к посту.
6. Открыть кабинет пользователя.

**Результат**: +2 к счетчику (пост+коммент).
**Ожидаемый результат**: +1 к счетчику, за счёт публикации нового поста.

## Переход на страницу настроек

**Проблема**: Иконка-ссылка в настройки имеет маленький масштаб нажатия

**Воспроизведение**:
1. Открыть приложение.
2. Открыть кабинет пользователя.
3. Попытаться открыть страницу настроек используя верхнюю часть иконки.

**Результат**: Ссылка не активируется/Зайти на страницу настроек невозможно.
**Ожидаемый результат**: Область активации перехода в настройки, на весь масштаб иконки.

## Поля "Тег" 

Проблема: Неправильное заполнение поля "Тег" приводит к ошибке

1. Открыть приложение.
2. Создать пост.
2.1. В поле "Тег", после написания тега, нажать клавишу перехода строки (Enter ↵).
3. Попытаться опубликовать пост.

**Результат**: Публикация невозможна, сообщение: "Не правильный вызов апи"
**Ожидаемый результат**: 
1) Публикация прошла успешно
2) Пункт (2.1.) -  клавиша перехода строки (Enter ↵) сохраняет тег и создает новый.

**Comment by yurivlad** [comment]
По поводу счетчика постов - так работает платформа, разделения на количество постов и количества коментов нет

**Comment by BaroH4er** [comment]
Перепроверка.
- [ ] ~Счетчик постов~
- [ ] Переход на страницу настроек
- [ ] Поля "Тег"
