### ISSUE TITLE
Внедрить пуш уведомления и их настройки

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/golos-android#36]
1. Внедрить настройки реалтайм уведомлений:
В настройках профиля есть разделение настройк на общие, просмотр ленты,  кним добавить раздел уведомления. По тапу на "Уведомления" переходит редирект на отдельную страницу
настроек -Уведомления
 - текст "Онлайн уведомления на Golos.io"
"Звук"
- [x] Воспроизводить звук при получении всех новых уведомлений  - Вкл\ Выключенно -переключается слайдером. По умолчанию все звуки отключены. Звук когда аппа не перед глазами.
текст "Какие уведомления вы получаете"
- [x] upvote статьи -Вкл\ Выключенно -переключается слайдером
- [x] Перевод (Трансфер) -Вкл\ Выключенно -переключается слайдером
- [x] Новый комментарий -Вкл\ Выключенно -переключается слайдером

![image](https://user-images.githubusercontent.com/30616421/36588376-937a510e-1890-11e8-8721-e0fa808f04c1.png)

2. Внедрить приоритетные реалтайм уведомления
возникают в активном и неактивном состоянии приложения.
- upvote статьи - уведомление
- новый комментарий
- трансфер уведомление

- [x] 1. **upvote статьи - online уведомление**
У пользователя всплывает окно уведомления с количеством апвоутов за пост, если у статьи появились новые апвоуты.
Окно содержит в себе ссылку на пост за который пришел апвоут и количество апвоутов.
Окно пропадает в течение 5 секунд, если окно открыто.
При нажатии на окно уведомления происходит переход за пост.
- Окно уведомления вида имеет вид:
Иконка апвоута+текст "За ваш пост (ссылка) проголосовали "73" (счетчик) раза."
- Если апвоут один нотификация имеет вид:
userpic+иконка+username поддержал ваш пост (ссылка)
- Если пост получил флаг (downvote) нотификация имеет вид:
Иконка флага+текст “Ваш пост (ссылка) получил 2 (счетчик) флага”
- Если флаг один нотификация имеет вид:
userpic+username поставил флаг вашему пост (ссылка)

- [x] 2. **Новый комментарий**
При поступлении нового комментария к посту или комментарию пользователя всплывает окно уведомления. При нажатии на уведомление пользователь переходит на комментарий.
Всплывающие онлайн уведомление содержит:
username+икона+userpic
ответил на ваш пост\ комментарий (ссылка на пост\комментарий)

- [x] 3. **Трансфер уведомление**  (сделать вместе с функционалом кошелька)
При поступлении новых средств на счет у пользователя всплывает окно уведомления, в котором содержится:
username от кого пришел трансфер + его юзерпик
сумма трансфера
Окно уведомления вида - Userpic+username-текст -сумма. Пример “Пользователь перевел вам __сумму.”
При нажатии на уведомление происходит редирект на историю трансферов  на стр кошелька.

**Comment by BaroH4er** [comment]
Тестирование завершено. Ошибок нет.
<hr/>

- [x] upvote статьи - online уведомление
- [x] Новый комментарий
- [x] Трансфер уведомление

<hr/>

**Comment by jevgenika** [comment]
- [ ] Поправить текст уведомлений
<string name="user_voted_on_post">%s лайкнул(а) ваш <![CDATA[<a href = "%s">пост</>]]></string>
заменить на -username поддержал ваш пост
<string name="user_downvoted_on_post">%s поставил(а) флаг вашему <![CDATA[<a href = "%s">посту</>]]></string>
заменить на  -user  негативно отреагировал (а) на ваш пост (комментарий)

- [ ] заверстать окна уведомлений относительно новому дизайну

**Comment by BaroH4er** [comment]
Тестирование завершено. В рамках тестирования этого таска, были выявлены и исправлены следующие ошибки: 

***A. Уведомление не пропадает после перехода.***
**Проблема**: если прочитать уведомление, и вернутся через кнопку возврата, оно все ещё висит. _Приложение открыто._

1. Открыть приложение, оставаться на окне ленты.
2. Оставить комментарий под постом тестируемого аккаунта или отправить любое другое уведомление. 
3. Дождаться и активировать уведомление (перейти по ссылки).
4. Вернутся назад с помощью кнопки возврата в левом верхнем углу окна.

**Результат**: уведомление все ещё висит.
**Ожидаемый результат**: после прочтения, нотификация закрывается.
_Примечание: так же уведомления не исчезают из окна списка нотификаций._

- [x] Исправлено

<hr/>

***B. Показать ещё _0_ нотификация***
**Проблема**: зачем то отображается ссылка на список уведомлений, при всего одном уведомлении.  _Приложение открыто._

1. Открыть приложение, оставаться на окне ленты.
2. Убедится что на тестируемом аккаунте нет уведомлений.
2. Оставить комментарий под постом тестируемого аккаунта или отправить любое другое уведомление. 
3. Дождаться уведомления.

**Результат**: окно уведомления предлагает перейти к списку уведомлений.
**Ожидаемый результат**: при единственной активной нотификации, ссылки на список уведомлений - нет.  

- [x] Исправлено

<hr/>

- [x] Нотификация апвоута.
- [x] Нотификация флага.
- [x] Нотификация ответа
- [x] Нотифкация трансфера: _"при нажатии на уведомление происходит переход в список транзакций"_ - невозможно из-за отсутствия в релизной версии "списка транзакций"
