### ISSUE TITLE
Поправить стр профиля пользователя

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/golos-android#41]
в профиля пользователя должны быть 3 закладки: Посты, Ответы. Информация
- [x]  Вместо закладки кошелек вставить закладку информация
![image](https://user-images.githubusercontent.com/30616421/35631050-8ed2af8a-06ab-11e8-8f7e-02f20ebcc7aa.png)
Закладка информация содержит:
- Город
- ссылка на сайт
- дата регистрации на голосе

- [x] Кошелек перенести под вкладками "Посты, Подписчики, Подписки"
реализовать переход в кошелек 
![image](https://user-images.githubusercontent.com/30616421/35631294-28fef50a-06ac-11e8-8785-5a7266053691.png)

**Comment by BaroH4er** [comment]
Тестирование завершено. Ошибок нет.
