### ISSUE TITLE
Добавить настройку цифр после запятой

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/golos-android#44]
по умолчанию пользователя показываем 3 знака - 0.01 MG (MVests) 3 знака
0.1 MGests (MVests) 2 знака показывать 
Добавить настройки
![image](https://user-images.githubusercontent.com/6249597/36040216-ea3809d4-0dd5-11e8-94e1-a59f9ebf2b3f.png)

**Comment by BaroH4er** [comment]
Некорректное отображение в настройках профиля: 

![image](https://user-images.githubusercontent.com/21989598/38360305-6f3195e8-38d2-11e8-8cf6-cfe4cd6d2043.png)

- [ ] Добавить стрелку вниз

**Comment by BaroH4er** [comment]
Тестирование завершено. Ошибок нет.
