### ISSUE TITLE
Сделать поиск по пользователям

### ISSUE THREAD

**Issue by yurivlad** [GolosChain/golos-android#45]
Сделать поиск по пользователям на экране поиска тегов (вертикального списка с поиском).
Будет 2 закладки на экране - поиск по тегам и поиск по пользователям - по тапу на закладке переключается режим, при этом как результаты  поиска так и содержимое строки поиска сохраняются для каждой вкладки между переключениями.
При введени пользователем букв обновляется список найденных аккаунтов. Между введением буквы и собственно запросом сделать ожидание - 150 - 300 мс, если в это время юзер ввел следующую букву - не делать запрос на сервер, если ожидание больше - считать это введенной строкой и запрос делать.
 Если введенноая строка не соответствует правилам именования юзера на голосе - показывать пустую строку, обрабатывать локально.

**Comment by BaroH4er** [comment]
Тестирование завершено. Ошибок нет.
