### ISSUE TITLE
Запуск приложения с внешних ссылок

### ISSUE THREAD

**Issue by baybak** [GolosChain/golos-android#51]
Многие приложения при переходе с внешних ссылок предлагают запускать своё приложение при переходи по этим ссылкам.
Будет гораздо удобнее если при клики на ссылки вида golos.io и goldvoice.club в телеграме или в браузере будет открывать приложение голоса.

**Comment by jevgenika** [comment]
@baybak задача дублирует https://github.com/GolosChain/tolstoy/issues/568
переход в приложение через редиректом из ссылок golos.io в разработке
