### ISSUE TITLE
Неверные уведомления

### ISSUE THREAD

**Issue by gropox** [GolosChain/golos-android#59]
Написал пост. Пользователь "А" прокомментировал пост. Я получил уведомление "А answered your post". После чего другие пользователи проголосовали за пост, но я все время получаю уведомление "А answered your post". 

Ну и хотелось бы отключаемые уведомления. Особенно нудно, когда первый день за пост голосуют. Как то группировать уведомления.

**Comment by BaroH4er** [comment]
@gropox приветствую! Можно уточнить устройство и версию браузера?

**Comment by gropox** [comment]
Google Pixel XL 1, Android 8, Chrome. Хотя собственно пользовался я андроид приложением.

**Comment by gropox** [comment]
![screenshot_20180608-194621-01](https://user-images.githubusercontent.com/26039472/41172865-74c95224-6b55-11e8-93ee-19cfd0b20b2c.jpeg)

Я от имени bopox прокомментировал свой пост  @ropox/workers,  мне пришло уведомление, как на скриншоте. Потом зашел от имени tolstoy и поставил апвот. Телефон пикнул, экран активировался, на экране все еще то же уведомление, что в начале. Среди уведомлений нету vote уведомлений. Видимо приложение на них реагирует, но не показывает.

**Comment by gropox** [comment]
Особенно нудно первые пару часов после написания поста. Телефон пищит нещадно, из за голосующих, а показывает что комментировали.

**Comment by yurivlad** [comment]
В приложений  есть настройки нотификаций - и, по умолчанию, нотификация госования не включена - т.е. не отображается.
Но есть баг, если первой нотификацией была нотификация, которая отображается, а следующей - которая была отключена - телефон покажет первую,  при получении отключенной  в настройках нотификации. 
Исправление бага будет в следующей версии приложения.

**Comment by gropox** [comment]
С трудом нашёл настройки. В закладке с профилем шестерёнка не реагирует напы по ней. А вот на экране с кошельком можно настройки открыть и точно, там vote отключены. Включил, попробую так. Все равно пищит, так хоть по делу.

**Comment by jevgenika** [comment]
@gropox в обновленной версии приложения баг поправлен
