### ISSUE TITLE
Добавить возможность реблога поста

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/golos-android#60]
- [x]  Доработать java библиотеку, добавив возможность сделать реблог

**Comment by yurivlad** [comment]
1. Небходимо описать, что произойдет по нажатию кнопки реблога:
а)будет ли индикация прогресса
б)будет ли сообщение о успехе или неудаче
с)будет ли меняться или исчезать иконка реблога после реблога.
2. Апвоут и дизлайк.
а) по нажатии дизлайка - что произойдет?
б)будет ли индикация прогресса апвоута или дизлайка
с)Если идет прогресс апвоута показывать ли кнопку дизлайка и наоборот.
д)будет ли меняться иконки по успеху апвоута или дизлайка

Добавление доп иконок не поместиться на некоторых экранах. Что делать тогда?

**Comment by jevgenika** [comment]
Ответы на вопросы:
а) индикация прогресса -показываем в сообщениях об успехе публикации
б)будет ли сообщение о успехе или неудаче -да текст выше
с)будет ли меняться или исчезать иконка реблога после реблога - иконка реблока становиться активной после успешной совершенной функции

Пользователь нажамает кнопку реблога на экране ленты/поста
1. видит экран диалога 
Текст: Заголовок -Поделиться этой записью 
Ответы: Поделиться/ Отмена
2. 1. При успешной публикации пользовтаелей на экране лент/ поста видит сообщение -
Текст: Запись опубликована.
Теперь эта запись появится в ленте ваших подписчиков.
2. 2. Текст сообщения при неудачной попытке реблога
Запись не опубликована.
Попробуйте еще раз.

**Comment by yurivlad** [comment]
а)что будет с кнопкой реблога, если на нее нажать? она не измениться, она исчезнет, может на ее месте появится кругляшь прогресса
с)Дизайн "активной кнопки" ?

**Comment by jevgenika** [comment]
а)что будет с кнопкой реблога, если на нее нажать?
- тап по кнопке реблога -вызывает окно поделиться с записью
-тап по активной кнопке реблога вызывает окно - подсказку с текстом. 
> Вы уже поделились этой записью. Отменина репоста в этой версии недоступна.

кнопка не измениться, не исчезнет.

с)Дизайн "активной кнопки"  -активная кнопка закрашивается.

**Comment by yurivlad** [comment]
а)Если нажать на кнопку реблога, пока идет запрос, все обновляется - мне показывать крутящийся кругляшь прогресса на месте кнопки реблога, как с голосованием?

Также вопрос, если юзер не залогинен показывать кнопку реблога?

**Comment by jevgenika** [comment]
Можем показать загрузку прогресса, после успешной публикации реблога потом индикация прогресса -показываем в сообщениях об успехе публикации.

Если юзер не залогинен показываем кнопку реблога, по тапу выводим сообщение:
> Необходимо войти в приложение для этого дейтсвия.

**Comment by yurivlad** [comment]
"тап по кнопке. Появляется окно с вопросом. Если юзер согласен - кнопка меняется на кругляш. По успеху - кругляшь меняется на окрашенную кнопку."
Если юзер не залогинен - кнопку мы не прячем

**Comment by jevgenika** [comment]
@daryasattarova да, все верно реблог поста,  должен отображаться в своей ленте во вкладке с постами на профиле

**Comment by daryasattarova** [comment]
1. при просмотре своего поста/при нахождении в своей ленте в профиле, кнопку реблога не отображаем
2. при успешном реблоге, пост должен отобразиться в своей ленте на профиле

**Comment by jevgenika** [comment]
- [ ] Добавить окно диалога для реблога

- Заголовок
Поделиться этим постом
- Текст
Подтвердите, пожалуйста, что хотите поделиться этим постом
- Кнопки
 Отмена, Поделиться


- [ ] Добавить всплывающее окно после успешного реблога
текст
Запись успешно опубликована.
Теперь этот репост этой записи появится в спсике ваших постов и ленте ваших подписчиков.

**Comment by daryasattarova** [comment]
1. добавить отображение реблога в ленте/посте, если юзер, на которого ты подписан, сделал реблог чьего-то поста
2. при просмотре своего поста кнопку реблога не отображаем. убрать иконку реблога во вкладках "комментарии", "ответы"
3. тап по активной кнопке реблога должно вызывать окно - подсказку с текстом "Вы уже поделились этой записью. Отменение репоста в этой версии недоступна."

**Comment by daryasattarova** [comment]
описка в тексте (смотреть пункт 3 выше)
