### ISSUE TITLE
пофиксить баг с неполным списком отображение коментариев

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/golos-android#65]
на экране ответов отображается не полный список комментариев из чейна
нужно пофиксить баг

**Comment by BaroH4er** [comment]
Тестирование завершено. В рамках ишью и проверки аккаунтов где были замечены проблемы - **ошибок не обнаружено**. В перспективе будущих изменений дизайна io, думаю стоит внести изменения на странице пользователя во вкладке "Ответы", в приложении. в данный момент:
>вкладка "ответы" в приложении == вкладка "комментарии" на io.

Было замечено что в будущем дизайне на io, вкладка "комментарии" - отсутствует. Что означает, отсутствия функционала на io который по прежнему будет функционировать в приложении. @jevgenika думаю необходимо реализовать  вкладка "ответы" в приложении == вкладка "ответы" на io.

**Comment by jevgenika** [comment]
@BaroH4er вкладка переименована
доп вкладка отдельным таском
