### ISSUE TITLE
Интеграция с микросервисами

### ISSUE THREAD

**Issue by yurivlad** [GolosChain/golos-android#73]
Сделать интеграцию с 

- [x] Гейтом (авторзация)
- [x] Пуш сервисом
- [ ]  Сервисом сохранения настроек
- [x]  Cервисом истории эвентов

**Comment by jevgenika** [comment]
https://github.com/GolosChain/golos-android/issues/147

**Comment by jevgenika** [comment]
дубль https://github.com/GolosChain/golos-android/issues/148
