### ISSUE TITLE
Заменить окно голосование за приложениие

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/golos-android#74]
- [x] Заменить окно голосование за приложение соответсвенно готовому дизайну окна
- [ ] оставить 2 кнопки для голосование -проголосовать сейчас, проголосовать позже

**Comment by yurivlad** [comment]
https://projects.invisionapp.com/d/main#/console/14771727/307768891/inspect
Решили оставить 3 кнопки, т.к. при переустановке приложения проголосовавшему пользователю будут показываться предложение о голосовании без возможности закрыть диалог навсегда.
