### ISSUE TITLE
Убрать кнопку "Открыть в приложении" на окне регистрации

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/golos-android#91]
Воспроизведение:
1. открыть приложение 
2. открыть окно логина
3. нажать кнопку "регистрация"

Ожидаемый результат: по окончанию загрузки окна появится кнопка "Открыть в приложении"
Реальный результат: данную кнопку нужно временно убрать
Комментарий: тот же сценарий для "Больше о Golos"

**Comment by jevgenika** [comment]
решено, неактуально
